"""Initial migration

Revision ID: 10db566fb4d3
Revises: 
Create Date: 2025-10-27 11:52:36.803368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10db566fb4d3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diagnoses', sa.Column('malignant_probability', sa.Float(), nullable=False))
    op.add_column('diagnoses', sa.Column('benign_probability', sa.Float(), nullable=False))
    op.add_column('diagnoses', sa.Column('confidence', sa.Float(), nullable=False))
    op.add_column('pictures', sa.Column('image_path', sa.String(), nullable=False))
    op.add_column('pictures', sa.Column('filename', sa.String(), nullable=False))
    op.alter_column('pictures', 'body_part_location',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pictures', 'body_part_location',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('pictures', 'filename')
    op.drop_column('pictures', 'image_path')
    op.drop_column('diagnoses', 'confidence')
    op.drop_column('diagnoses', 'benign_probability')
    op.drop_column('diagnoses', 'malignant_probability')
    # ### end Alembic commands ###
