"""add_is_pro_to_users

Revision ID: 77cbddfe060b
Revises: 9e1be52501da
Create Date: 2025-11-06 19:41:48.924834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77cbddfe060b'
down_revision: Union[str, None] = '9e1be52501da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pictures', sa.Column('skin_tone', sa.String(), nullable=True))
    
    # Add is_pro column as nullable first
    op.add_column('users', sa.Column('is_pro', sa.Boolean(), nullable=True))
    
    # Update existing users to have is_pro = False
    op.execute("UPDATE users SET is_pro = false WHERE is_pro IS NULL")
    
    # Make the column non-nullable
    op.alter_column('users', 'is_pro', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_pro')
    op.drop_column('pictures', 'skin_tone')
    # ### end Alembic commands ###
